Work Page
IfzaRasool/Portfolio-mobile-version-skeleton pull request #2
Opened 2021-11-30 08:33 UTC by IfzaRasool

Work Page is a recent post page where you upload your post with a post description.

2021-11-30 11:05 UTC, emmanuellekamwa requested changes
**STATUS: CHANGES REQUESTED ❌⛔**
Hello @IfzaRasool 👋
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._
- Your readme file does not really look presentable. Please check this [link](https://github.com/microverseinc/readme-template) so as to do a good readme.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 11:05 UTC, emmanuellekamwa commented on index.html
> +        <h2 class="work-text">Work</h2>
- [ ] The list of social medias and the work title are not centrally aligned. Please try and fix that.

2021-11-30 21:56 UTC, lily-coder approved these changes
Hi @IfzaRasool , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![image](https://user-images.githubusercontent.com/63964646/144134468-6c2820cc-b33d-4c67-9926-7dbb0df3a7e4.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 22:03 UTC, merged

2021-12-01 13:46 UTC, IfzaRasool commented on index.html
> +        </div>
### ok

2021-12-01 13:46 UTC, IfzaRasool commented on index.html
> +        </div>
> ssss

2021-12-01 13:47 UTC, IfzaRasool commented on index.html
> +        </div>
> ssssssssssssss``

2021-12-01 13:47 UTC, IfzaRasool commented on index.html
> +        </div>
sssssssssssss

- [ ] ssss