Contact form
IfzaRasool/Portfolio-mobile-version-skeleton pull request #3
Opened 2021-12-02 20:31 UTC by IfzaRasool

Contact Form: with the help of the contact form easily contact with admin and send any query and ask whatever you want. here we use just two languages HTML and CSS with proper semantic rules and add some graphical images for the interface.

2021-12-06 11:55 UTC, DammyShittu requested changes
Hi @IfzaRasool , 

Amazing job so far! 👏 

You have a very nice UI design and I can confirm that you have put in a lot of work to build your portfolio 👍 

However, there are some issues that you still need to work on to go to the next project but you are **ALMOST THERE**!

## REQUIRED CHANGES ♻️

- Commit messages are a great way to describe what has been done at a particular checkpoint.
Kindly check this [article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#5-basic-rules-to-follow-in-microverse-projects) to see examples of how to write descriptive commit messages.

_I have left some comments to help you improve your project, kindly check the comments under the review._

# Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-06 11:55 UTC, DammyShittu commented on index.html
> +        <form class="contact-form" action="#" method="post">
- [ ] Kindly follow the requirement that says `Collect data by using the Formspree service`. You can navigate to the Formspree website using this [link](https://formspree.io/html). 😀

2021-12-06 11:55 UTC, DammyShittu commented on index.html
> +            <button class="contact-btn" type="button">See Project</button>
- [ ] To validate user input, kindly add the `required` attribute to all the text fields. This will make sure that no field is submitted without the appropriate content/value 👍 

- [ ] Kindly use `submit` type on the `button` element. A button with the `submit` type within a form has a default behaviour of submitting the form as long as all validations have been met. You can also decide not to add a `type` attribute to the `button` element as the default `type`, when it's not specified, is `submit`. 😉

2021-12-08 09:05 UTC, ShoiraTa commented
### **STATUS: APPROVED  ✔️** 
------
Hi team,  

Your project is complete! Congratulations!  🎉💯🌟 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-08 09:24 UTC, merged